import { createFileRoute } from "@tanstack/react-router";
import { AppLayout } from "@/components/AppLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Car, RefreshCw, ReceiptText, Download, Eye, Calendar, ChevronDown } from "lucide-react";

export const Route = createFileRoute("/app/receipts")({
  component: Receipts,
});

const txns = [
  { id: "PC-99281", plate: "ABC-1234", duration: "5h 31m", amount: "$24.83" },
  { id: "PC-99280", plate: "XYZ-8877", duration: "2h 15m", amount: "$10.50" },
  { id: "PC-99279", plate: "GHJ-4412", duration: "0h 45m", amount: "$5.00" },
  { id: "PC-99278", plate: "JKL-0092", duration: "12h 02m", amount: "$54.10" },
  { id: "PC-99277", plate: "UIO-3345", duration: "3h 20m", amount: "$15.00" },
];

function Receipts() {
  return (
    <AppLayout searchPlaceholder="Search transactions or plate numbers...">
      <div className="flex items-start justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold">Receipt Generation</h1>
          <p className="text-muted-foreground mt-1">Process and manage parking transaction invoices.</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline"><RefreshCw className="h-4 w-4 mr-2" /> Sync Transactions</Button>
          <Button className="bg-sidebar hover:bg-sidebar/90 text-sidebar-foreground"><ReceiptText className="h-4 w-4 mr-2" /> Generate Receipt</Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <Card className="p-6">
          <div className="flex items-center justify-between mb-5">
            <div className="flex items-center gap-2"><Car className="h-5 w-5" /><div><div className="text-xs text-muted-foreground">TRANS_ID: PC-99281</div><div className="text-xl font-bold">Invoice Preview</div></div></div>
            <Badge className="bg-primary/15 text-primary">PAID</Badge>
          </div>

          <div className="border-2 border-dashed rounded-lg p-6 text-center bg-muted/30">
            <div className="text-xs uppercase tracking-widest text-muted-foreground">Plate Number</div>
            <div className="text-5xl font-bold mt-2">ABC-1234</div>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-5 text-sm">
            <div><div className="text-xs text-muted-foreground uppercase">Entry Time</div><div className="font-semibold mt-1">Oct 12, 09:14 AM</div></div>
            <div><div className="text-xs text-muted-foreground uppercase">Exit Time</div><div className="font-semibold mt-1">Oct 12, 02:45 PM</div></div>
            <div className="pt-3 border-t"><div className="text-xs text-muted-foreground uppercase">Total Duration</div><div className="font-semibold mt-1">5h 31m</div></div>
            <div className="pt-3 border-t"><div className="text-xs text-muted-foreground uppercase">Rate Applied</div><div className="font-semibold mt-1">$4.50 / hour</div></div>
          </div>

          <div className="bg-muted/50 rounded-lg p-5 mt-5 flex items-center justify-between">
            <div><div className="font-semibold">Amount Paid</div><div className="text-xs text-muted-foreground">Includes 5% city tax</div></div>
            <div className="text-4xl font-bold">$24.83</div>
          </div>

          <Button variant="outline" className="w-full mt-5 h-11"><Download className="h-4 w-4 mr-2" /> Download PDF Receipt</Button>
          <p className="text-xs italic text-center text-muted-foreground mt-3">Generated by ParkCar City Management Engine v4.2</p>
        </Card>

        <div className="space-y-5">
          <div className="grid grid-cols-2 gap-4">
            <button className="bg-card border rounded-lg px-4 py-3 text-sm flex items-center justify-between"><span>All Parking Lots</span><ChevronDown className="h-4 w-4" /></button>
            <button className="bg-card border rounded-lg px-4 py-3 text-sm flex items-center gap-2"><Calendar className="h-4 w-4" /> Last 24 Hours</button>
          </div>

          <Card className="p-6">
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-xl font-bold">Transaction History</h2>
              <button className="text-sm font-medium text-primary hover:underline">View All Records</button>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs uppercase text-muted-foreground border-b">
                    <th className="pb-3 font-medium">Transaction ID</th>
                    <th className="pb-3 font-medium">Plate</th>
                    <th className="pb-3 font-medium">Duration</th>
                    <th className="pb-3 font-medium">Amount</th>
                    <th className="pb-3 font-medium"></th>
                  </tr>
                </thead>
                <tbody>
                  {txns.map((t) => (
                    <tr key={t.id} className="border-b last:border-0">
                      <td className="py-4">{t.id}</td>
                      <td className="py-4"><span className="bg-muted px-2 py-1 rounded text-xs font-semibold">{t.plate}</span></td>
                      <td className="py-4 text-muted-foreground">{t.duration}</td>
                      <td className="py-4 font-bold">{t.amount}</td>
                      <td className="py-4"><button className="text-muted-foreground hover:text-foreground"><Eye className="h-4 w-4" /></button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>

          <div className="grid grid-cols-2 gap-4">
            <Card className="p-5 bg-primary/10">
              <div className="text-xs text-muted-foreground">TOTAL REVENUE (TODAY)</div>
              <div className="text-2xl font-bold mt-1">$4,284.50</div>
              <div className="text-xs text-primary mt-1">↗ 12% vs yesterday</div>
            </Card>
            <Card className="p-5 bg-sidebar text-sidebar-foreground">
              <div className="text-xs text-sidebar-foreground/60">RECEIPTS ISSUED</div>
              <div className="text-2xl font-bold mt-1">184</div>
              <div className="text-xs text-sidebar-foreground/70 mt-1">✓ All verified today</div>
            </Card>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
